//! Generated Batch A native-link probe.
//! Regenerate with `slatec-corpus generate-raw-batch-a --offline`.

#![cfg(all(
    feature = "raw-canonical-link-tests",
    target_arch = "x86_64",
    target_env = "gnu",
    target_os = "windows"
))]

#[test]
fn canonical_symbols_link() {
    slatec_src::ensure_linked();
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::ortran as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchbs as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchcm as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchfd as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchfe as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchia as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchic as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchid as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchim as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::pchsp as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::approximation::pcoef as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::poch as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::poch1 as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::pde::fishpack::poistg as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::polcof as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::approximation::polfit as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::polint as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::polyvl as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::quadrature::ppqad as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::interpolation::ppval as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::psifn as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::approximation::pvalue as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::quadrature::qmomo as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::qzhes as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::qzit as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::qzval as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::qzvec as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::statistics::rand as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::ratqr as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rc as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rc3jj as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rc3jm as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rc6j as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rd as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rebak as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rebakb as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::reduc as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::reduc2 as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rf as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::rfftb1 as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::rfftf1 as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::rffti1 as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rg as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::statistics::rgauss as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rgg as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::rj as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rs as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rsb as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rsg as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rsgab as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rsgba as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rsp as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rst as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::rt as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::statistics::runif as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::approximation::sbocls as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::approximation::sbols as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::schdc as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::schdd as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::schex as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::schud as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::sgbco as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::sgbdi as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::sgbfa as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::sgbsl as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sgeco as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sgedi as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::eigen::sgeev as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sgefa as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sgefs as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sgeir as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sgesl as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sglss as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::sgtsl as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::sinqb as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::sinqf as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::sinqi as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::sint as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::fftpack::sinti as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::ode::sintrp as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::sllti2 as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::snbco as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::snbdi as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::snbfa as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::snbfs as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::snbir as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::snbsl as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::spbco as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::spbdi as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::spbfa as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::banded::spbsl as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::special::spenc as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::spoco as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::spodi as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::spofa as *const () as usize);
    let _ = core::hint::black_box(slatec_sys::linear_algebra::dense::spofs as *const () as usize);
}
