//! Reviewed raw BLAS classification, documentation, and binding rendering.
//!
//! This is deliberately a narrow, source-hash-guarded promotion policy.  It
//! does not turn every routine in the historical "Linear algebra kernels"
//! catalogue family into BLAS: the multiprecision package and identities with
//! no selected executable source remain explicit non-promotions.

use crate::error::{CorpusError, Result};
use crate::hash;
use serde_json::{Value, json};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// The complete R2A public BLAS level-one set in the selected corpus.
pub const LEVEL1: &[&str] = &[
    "CAXPY", "CCOPY", "CROTG", "CSCAL", "CSROT", "CSSCAL", "CSWAP", "DASUM", "DAXPY", "DCDOT",
    "DCOPY", "DCOPYM", "DDOT", "DNRM2", "DQDOTA", "DQDOTI", "DROT", "DROTG", "DROTM", "DROTMG",
    "DS2Y", "DSCAL", "DSDI", "DSDOT", "DSMTV", "DSMV", "DSWAP", "ICAMAX", "ICOPY", "IDAMAX",
    "ISAMAX", "ISWAP", "SASUM", "SAXPY", "SCASUM", "SCNRM2", "SCOPY", "SCOPYM", "SDOT", "SDSDOT",
    "SNRM2", "SROT", "SROTG", "SROTM", "SROTMG", "SS2Y", "SSCAL", "SSDI", "SSMTV", "SSMV", "SSWAP",
];

/// The complete R2A public BLAS level-two set in the selected corpus.
pub const LEVEL2: &[&str] = &[
    "CGBMV", "CGEMV", "CGERC", "CGERU", "CHBMV", "CHEMV", "CHER", "CHER2", "CHPMV", "CHPR",
    "CHPR2", "CTBMV", "CTBSV", "CTPMV", "CTPSV", "CTRMV", "CTRSV", "DGBMV", "DGEMV", "DGER",
    "DSBMV", "DSPMV", "DSPR", "DSPR2", "DSYMV", "DSYR", "DSYR2", "DTBMV", "DTBSV", "DTPMV",
    "DTPSV", "DTRMV", "DTRSV", "SGBMV", "SGEMV", "SGER", "SSBMV", "SSPMV", "SSPR", "SSPR2",
    "SSYMV", "SSYR", "SSYR2", "STBMV", "STBSV", "STPMV", "STPSV", "STRMV", "STRSV",
];

/// The complete R2A public BLAS level-three set in the selected corpus.
pub const LEVEL3: &[&str] = &[
    "CGEMM", "CHEMM", "CHER2K", "CHERK", "CSYMM", "CSYR2K", "CSYRK", "CTRMM", "CTRSM", "DGEMM",
    "DSYMM", "DSYR2K", "DSYRK", "DTRMM", "DTRSM", "SGEMM", "SSYMM", "SSYR2K", "SSYRK", "STRMM",
    "STRSM",
];

/// Returns the reviewed BLAS level for a public R2A identity.
pub fn level(routine: &str) -> Option<u8> {
    if LEVEL1.contains(&routine) {
        Some(1)
    } else if LEVEL2.contains(&routine) {
        Some(2)
    } else if LEVEL3.contains(&routine) {
        Some(3)
    } else {
        None
    }
}

/// Returns the canonical level module for a reviewed identity.
pub fn module(routine: &str) -> Option<&'static str> {
    match level(routine) {
        Some(1) => Some("blas::level1"),
        Some(2) => Some("blas::level2"),
        Some(3) => Some("blas::level3"),
        _ => None,
    }
}

/// Returns the public and provider feature for a level.
pub fn feature(routine: &str) -> Option<&'static str> {
    match level(routine) {
        Some(1) => Some("blas-level1"),
        Some(2) => Some("blas-level2"),
        Some(3) => Some("blas-level3"),
        _ => None,
    }
}

/// Source-hash guard input for the family-level authored review policy.
pub fn source_manifest(records: &[Value]) -> String {
    let mut entries = records
        .iter()
        .filter(|record| level(&field(record, "routine")).is_some())
        .filter(|record| field(record, "historical_role") == "user_callable")
        .filter(|record| field(record, "generated_declaration_status") == "generated_abi_validated")
        .map(|record| {
            format!(
                "{}\0{}\0{}\n",
                field(record, "routine"),
                field(record, "source_hash"),
                field(record, "canonical_provider"),
            )
        })
        .collect::<Vec<_>>();
    entries.sort();
    hash::bytes(entries.concat().as_bytes())
}

/// Renders the canonical reviewed `slatec_sys::blas` re-export module.
///
/// The declarations remain owned by the ABI-shaped generated modules.  This
/// prevents a second `extern` declaration while giving reviewed paths their
/// own complete raw Rustdoc contract.
pub fn render_module(records: &[Value]) -> String {
    let mut output = String::from(
        "//! Canonical reviewed raw BLAS declarations.\n//!\n//! This file is generated by `slatec-corpus generate-raw-api-inventory --offline`.\n//! Do not edit it directly; the R2A source-hash-guarded BLAS policy and selected\n//! source metadata are the review inputs.\n\n",
    );
    for (level_number, routines) in [(1_u8, LEVEL1), (2, LEVEL2), (3, LEVEL3)] {
        let gate = if level_number == 1 {
            format!(
                "#[cfg(any(\n    feature = \"blas-level{level_number}\",\n    feature = \"raw-family-blas-level{level_number}\",\n    feature = \"raw-family-blas-complex\"\n))]"
            )
        } else {
            format!(
                "#[cfg(any(feature = \"blas-level{level_number}\", feature = \"raw-family-blas-level{level_number}\"))]"
            )
        };
        output.push_str(&format!(
            "/// Reviewed public BLAS Level {level_number} raw routines.\n{gate}\npub mod level{level_number} {{\n"
        ));
        let mut items = records
            .iter()
            .filter(|record| level(&field(record, "routine")) == Some(level_number))
            .filter(|record| {
                field(record, "reviewed_declaration_status") == "reviewed_public_driver"
            })
            .collect::<Vec<_>>();
        items.sort_by_key(|record| field(record, "routine"));
        assert_eq!(
            items.len(),
            routines.len(),
            "reviewed BLAS policy did not render its complete level"
        );
        for record in items {
            render_routine(&mut output, record, level_number);
        }
        if level_number == 1 {
            output.push_str(
                "    /// Complex-return BLAS Level 1 functions.\n    #[cfg(feature = \"raw-family-blas-complex\")]\n    pub use crate::abi_bindings::blas::{cdcdot, cdotc, cdotu};\n\n",
            );
        }
        if output.ends_with("\n\n") {
            output.pop();
        }
        output.push_str("}\n\n");
    }
    if output.ends_with("\n\n") {
        output.pop();
    }
    output
}

/// Renders the narrow generated declaration owner used by the reviewed BLAS
/// surface.  The broad ABI-shaped modules remain available under explicit
/// `raw-ffi-*` gates; BLAS family gates must not compile that whole layer just
/// to re-export 121 reviewed routines.
pub fn render_generated_module(sys_dir: &Path, records: &[Value]) -> Result<String> {
    let mut output = String::from(
        "//! Narrow generated declaration owner for reviewed BLAS routines.\n//!\n//! This file is generated by `slatec-corpus generate-raw-api-inventory --offline`.\n//! It is an implementation detail of the canonical `slatec_sys::blas` paths;\n//! broad ABI-shaped generated modules remain separately gated.\n\n#![allow(unused_imports)]\n\nuse crate::{Complex32, Complex64, FortranCharacterLength, FortranInteger, FortranLogical};\nuse core::ffi::c_char;\n\n",
    );
    for level_number in 1..=3 {
        output.push_str(&format!(
            "#[cfg(any(feature = \"blas-level{level_number}\", feature = \"raw-family-blas-level{level_number}\"))]\nunsafe extern \"C\" {{\n"
        ));
        let mut items = records
            .iter()
            .filter(|record| level(&field(record, "routine")) == Some(level_number))
            .filter(|record| {
                field(record, "reviewed_declaration_status") == "reviewed_public_driver"
            })
            .collect::<Vec<_>>();
        items.sort_by_key(|record| field(record, "routine"));
        for record in items {
            output.push_str(&generated_declaration(sys_dir, record)?);
            output.push('\n');
        }
        output.push_str("}\n\n");
    }
    if output.ends_with("\n\n") {
        output.pop();
    }
    Ok(output)
}

/// Creates the machine-readable complete BLAS-family disposition report.
pub fn family_report(records: &[Value]) -> Value {
    let mut rows = records
        .iter()
        .filter(|record| field(record, "primary_family") == "Linear algebra kernels")
        .map(|record| {
            let routine = field(record, "routine");
            let disposition = if field(record, "reviewed_declaration_status")
                == "reviewed_public_driver"
            {
                "reviewed public BLAS routine"
            } else if matches!(routine.as_str(), "CDCDOT" | "CDOTC" | "CDOTU") {
                "unsupported ABI: complex-valued Fortran function return"
            } else if routine.starts_with("MP") {
                "not actually BLAS: multiprecision arithmetic subsidiary"
            } else if field(record, "raw_api_state") == "catalogue_only" {
                "missing or ambiguous symbol: no selected executable provider"
            } else {
                "unresolved BLAS classification"
            };
            json!({
                "routine":routine,
                "historical_role":field(record,"historical_role"),
                "program_unit_kind":field(record,"program_unit_kind"),
                "precision":field(record,"precision"),
                "blas_level":level(&routine),
                "operation_class":operation_class(&routine),
                "canonical_provider":field(record,"canonical_provider"),
                "source_hash":field(record,"source_hash"),
                "native_symbol":field(record,"native_symbol"),
                "generated_declaration_path":generated_path(record),
                "existing_family_declaration_paths":record.get("legacy_rust_paths").cloned().unwrap_or_else(|| json!([])),
                "safe_wrapper_status":field(record,"safe_wrapper_status"),
                "feature":field(record,"feature"),
                "provider_feature":field(record,"provider_feature"),
                "provider_closure":if level(&routine).is_some() {
                    format!("slatec-src feature `{}`", feature(&routine).expect("BLAS level has a feature"))
                } else {
                    "not available".to_owned()
                },
                "documentation_status":field(record,"documentation_status"),
                "test_coverage":{"compile":field(record,"compile_test_status"),"link":field(record,"link_test_status"),"runtime":field(record,"runtime_test_status")},
                "final_disposition":disposition,
                "exclusion_reason":field(record,"exclusion_reason"),
            })
        })
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| left["routine"].as_str().cmp(&right["routine"].as_str()));
    let counts = rows
        .iter()
        .fold(BTreeMap::<String, usize>::new(), |mut counts, row| {
            *counts.entry(field(row, "final_disposition")).or_default() += 1;
            counts
        });
    json!({
        "schema_id":"slatec-sys.raw-api.blas-family-report",
        "schema_version":"1.0.0",
        "scope":"Every catalogue identity classified by the R1 taxonomy as blas; no identity is silently omitted.",
        "disposition_counts":counts,
        "records":rows,
    })
}

fn render_routine(output: &mut String, record: &Value, level_number: u8) {
    let routine = field(record, "routine");
    let function = routine.to_ascii_lowercase();
    let source_file = field(record, "source_file");
    let source_link = source_link(&source_file);
    let routine_purpose = purpose(&routine);
    if level_number == 1 {
        output.push_str(
            "    #[cfg(any(feature = \"blas-level1\", feature = \"raw-family-blas-level1\"))]\n",
        );
    }
    output.push_str(&format!("    // raw-api-routine: {routine}\n"));
    doc_line(output, &format!("Original SLATEC routine `{routine}`."));
    doc_line(output, &routine_purpose);
    doc_line(
        output,
        &format!(
            "Mathematical operation: {}. BLAS Level {level_number}; scalar profile: `{}`.",
            operation_class(&routine),
            field(record, "precision")
        ),
    );
    doc_line(
        output,
        &format!(
            "Selected provider: `{}`; source: <{source_link}>; native symbol: `{}`.",
            field(record, "canonical_provider"),
            field(record, "native_symbol")
        ),
    );
    doc_line(
        output,
        "Supported ABI profile: `ffi-profile-gnu-mingw-x86_64` (GNU Fortran default INTEGER and trailing CHARACTER lengths).",
    );
    doc_line(output, "");
    doc_line(output, "# Arguments");
    for argument in strings(record.get("argument_order")) {
        doc_line(
            output,
            &format!("- `{argument}`: {}", argument_doc(&routine, &argument)),
        );
    }
    if field(record, "feature") == "raw-ffi-character" {
        doc_line(
            output,
            "- Hidden trailing `FortranCharacterLength` arguments: one follows the visible Fortran arguments for each CHARACTER flag, in visible flag order. Pass `1` for every one-byte flag buffer.",
        );
    }
    doc_line(output, "");
    doc_line(output, "# Safety");
    doc_line(
        output,
        "All scalar pointers must be non-null and valid for the documented read or write access. Every vector and matrix pointer must describe contiguous Fortran column-major storage with the stated leading dimensions and strides. For a strided vector with `N > 0`, make the complete source-defined extent accessible; positive increments need at least `1 + (N - 1) * INC` elements from the selected starting element. Zero and negative increments are accepted only where the selected routine's prologue permits them; this raw interface never normalizes them. Do not pass overlapping mutable operands unless the selected source explicitly permits that overlap. The native routine retains no pointer after return. The raw API does not serialize calls; callers must account for the linked SLATEC runtime and any broader process-global state.",
    );
    output.push_str(&format!(
        "    #[doc(inline)]\n    pub use crate::generated::blas::{function};\n\n"
    ));
}

fn generated_declaration(sys_dir: &Path, record: &Value) -> Result<String> {
    let symbol = field(record, "native_symbol");
    let marker = format!("    #[link_name = \"{symbol}\"]");
    let generated_dir = sys_dir.join("src").join("generated");
    let authoritative = fs::read_to_string(generated_dir.join("blas.rs"))?;
    let source = if authoritative.contains(&marker) {
        authoritative
    } else {
        fs::read_to_string(generated_dir.join(format!(
            "{}.rs",
            generated_module(&field(record, "generated_declaration_feature"))
        )))?
    };
    let start = source.find(&marker).ok_or_else(|| {
        CorpusError::Verification(format!(
            "BLAS generated declaration for {} has no source marker {symbol}",
            field(record, "routine")
        ))
    })?;
    let rest = &source[start..];
    let end = rest.find(';').map(|offset| offset + 1).ok_or_else(|| {
        CorpusError::Verification(format!(
            "BLAS generated declaration for {} is not terminated",
            field(record, "routine")
        ))
    })?;
    Ok(rest[..end].to_owned())
}

fn doc_line(output: &mut String, text: &str) {
    if text.is_empty() {
        output.push_str("    ///\n");
    } else {
        output.push_str("    /// ");
        output.push_str(text);
        output.push('\n');
    }
}

fn generated_module(feature: &str) -> &'static str {
    match feature {
        "raw-ffi-numeric-scalar-subroutines" => "numeric_scalar_subroutines",
        "raw-ffi-numeric-array-subroutines" => "numeric_array_subroutines",
        "raw-ffi-scalar-functions" => "scalar_functions",
        "raw-ffi-complex-arguments" => "complex_arguments",
        "raw-ffi-character" => "character",
        _ => panic!("reviewed BLAS routine lacks a generated ABI module"),
    }
}

fn generated_path(record: &Value) -> String {
    let feature = field(record, "generated_declaration_feature");
    match feature.as_str() {
        "raw-ffi-numeric-scalar-subroutines"
        | "raw-ffi-numeric-array-subroutines"
        | "raw-ffi-scalar-functions"
        | "raw-ffi-complex-arguments"
        | "raw-ffi-character" => format!(
            "slatec_sys::generated::{}::{}",
            generated_module(&feature),
            field(record, "routine").to_ascii_lowercase()
        ),
        _ => "not_generated".to_owned(),
    }
}

fn purpose(routine: &str) -> String {
    match operation_class(routine) {
        "AXPY vector update" => {
            "Computes `Y <- alpha * X + Y` for the selected scalar type.".to_owned()
        }
        "general matrix-matrix multiply" => {
            "Computes `C <- alpha * op(A) * op(B) + beta * C` in column-major storage.".to_owned()
        }
        "general matrix-vector multiply" => {
            "Computes `Y <- alpha * op(A) * X + beta * Y` in column-major storage.".to_owned()
        }
        "triangular solve" => {
            "Solves a triangular matrix equation in-place in the right-hand-side storage."
                .to_owned()
        }
        "triangular matrix multiply" => {
            "Multiplies a matrix or vector by a selected triangular matrix in-place.".to_owned()
        }
        other => format!("Executes the selected BLAS-family {other} operation."),
    }
}

fn operation_class(routine: &str) -> &'static str {
    if routine.ends_with("AXPY") {
        "AXPY vector update"
    } else if routine.ends_with("GEMM") {
        "general matrix-matrix multiply"
    } else if routine.ends_with("GEMV") {
        "general matrix-vector multiply"
    } else if routine.ends_with("TRSM")
        || routine.ends_with("TRSV")
        || routine.ends_with("TBSV")
        || routine.ends_with("TPSV")
    {
        "triangular solve"
    } else if routine.ends_with("TRMM")
        || routine.ends_with("TRMV")
        || routine.ends_with("TBMV")
        || routine.ends_with("TPMV")
    {
        "triangular matrix multiply"
    } else if routine.ends_with("COPY") || routine.ends_with("COPYM") {
        "vector copy"
    } else if routine.ends_with("SWAP") {
        "vector swap"
    } else if routine.ends_with("SCAL") || routine.ends_with("SSCAL") {
        "vector scaling"
    } else if routine.ends_with("DOT") || routine.ends_with("DOTA") || routine.ends_with("DOTI") {
        "dot product"
    } else if routine.ends_with("NRM2") {
        "Euclidean vector norm"
    } else if routine.ends_with("ASUM") {
        "sum of vector magnitudes"
    } else if routine.ends_with("AMAX") {
        "index of maximum vector magnitude"
    } else if routine.ends_with("ROTG") {
        "plane-rotation parameter generation"
    } else if routine.ends_with("ROTMG") {
        "modified plane-rotation parameter generation"
    } else if routine.ends_with("ROTM") {
        "modified plane rotation"
    } else if routine.ends_with("ROT") {
        "plane rotation"
    } else if routine.ends_with("GER") || routine.ends_with("GERC") || routine.ends_with("GERU") {
        "rank-one matrix update"
    } else if routine.ends_with("SYR2") || routine.ends_with("HER2") {
        "symmetric or Hermitian rank-two update"
    } else if routine.ends_with("SYR")
        || routine.ends_with("HER")
        || routine.ends_with("SPR")
        || routine.ends_with("HPR")
    {
        "symmetric or Hermitian rank-one update"
    } else if routine.ends_with("SYR2K") || routine.ends_with("HER2K") {
        "symmetric or Hermitian rank-2k update"
    } else if routine.ends_with("SYRK") || routine.ends_with("HERK") {
        "symmetric or Hermitian rank-k update"
    } else if routine.ends_with("SYMM") || routine.ends_with("HEMM") {
        "symmetric or Hermitian matrix multiply"
    } else if routine.ends_with("SYMV")
        || routine.ends_with("HEMV")
        || routine.ends_with("SBMV")
        || routine.ends_with("HBMV")
        || routine.ends_with("SPMV")
        || routine.ends_with("HPMV")
    {
        "symmetric or Hermitian matrix-vector multiply"
    } else if routine.ends_with("GBMV") {
        "general band matrix-vector multiply"
    } else {
        "selected BLAS helper"
    }
}

fn argument_doc(routine: &str, argument: &str) -> String {
    match argument {
        "N" => "Input operation order or vector element count. The selected routine may quick-return when it is non-positive.".to_owned(),
        "M" => "Input row count. Matrix leading dimensions and operand storage must be valid for this selected dimension.".to_owned(),
        "K" => "Input inner or band dimension used by the selected operation.".to_owned(),
        "INCX" if routine.ends_with("NRM2") => "Input vector storage increment for X. The selected norm source requires `INCX >= 1`; this raw interface does not normalize a zero or negative increment.".to_owned(),
        "INCX" | "INCY" => format!("Input vector storage increment for {}. Its permitted sign and traversal are defined by this routine's selected source prologue; this raw interface does not normalize zero or negative increments.", if argument == "INCX" { "X" } else { "Y" }),
        "LDA" | "LDB" | "LDC" => format!("Input leading dimension for the column-major {} operand. It must meet the selected source's dimension rule for the active flags.", &argument[2..]),
        "KL" | "KU" => "Input number of stored sub- or super-diagonals in general band storage.".to_owned(),
        "TRANS" | "TRANSA" | "TRANSB" => "Input one-byte CHARACTER flag selecting no-transpose, transpose, or (for complex routines) conjugate-transpose as accepted by the selected source; pass its trailing hidden length as `1`.".to_owned(),
        "UPLO" => "Input one-byte CHARACTER flag selecting the stored upper or lower triangle; pass its trailing hidden length as `1`.".to_owned(),
        "DIAG" => "Input one-byte CHARACTER flag selecting unit or non-unit diagonal treatment; pass its trailing hidden length as `1`.".to_owned(),
        "SIDE" => "Input one-byte CHARACTER flag selecting whether the matrix operand acts on the left or right; pass its trailing hidden length as `1`.".to_owned(),
        "ALPHA" | "BETA" => "Input scalar multiplier. It is read for the duration of the call and is not retained.".to_owned(),
        "SA" | "DA" | "CA" if routine.ends_with("ROTG") => "In/out scalar rotation-generator operand; the selected routine overwrites it with its documented transformed value.".to_owned(),
        "SB" | "DB" | "CB" if routine.ends_with("ROTG") => "In/out scalar rotation-generator operand; the selected routine overwrites it with its documented transformed value.".to_owned(),
        "SA" | "DA" | "CA" => "Input scalar multiplier. It is read for the duration of the call and is not retained.".to_owned(),
        "X" | "SX" | "DX" | "CX" => vector_doc(routine, argument, "X"),
        "Y" | "SY" | "DY" | "CY" => vector_doc(routine, argument, "Y"),
        "A" => matrix_doc(routine, "A"),
        "B" => matrix_doc(routine, "B"),
        "C" if routine.ends_with("ROTG") => "Output real rotation cosine written by the selected parameter generator.".to_owned(),
        "C" if routine.ends_with("ROT") => "Input real rotation cosine used for the selected plane rotation.".to_owned(),
        "C" => matrix_doc(routine, "C"),
        "AP" => "Packed symmetric, Hermitian, or triangular matrix storage. It is read or updated according to the selected operation and must contain the selected packed triangle.".to_owned(),
        "PARAM" | "DPARAM" | "SPARAM" => "In/out rotation-parameter array with the source-defined fixed layout; it must be writable for all documented parameter slots.".to_owned(),
        "S" if routine.ends_with("ROTG") => "Output rotation sine written by the selected parameter generator.".to_owned(),
        "S" if routine.ends_with("ROT") => "Input rotation sine used for the selected plane rotation.".to_owned(),
        "DC" | "DS" | "SC" | "SS" => "Input real rotation coefficient used for the selected plane rotation.".to_owned(),
        "DD1" | "DD2" | "DX1" | "DY1" => "In/out scalar used by the modified rotation parameter generator.".to_owned(),
        "DCR" | "DCI" => "Output real or imaginary component written by the selected extended complex dot helper.".to_owned(),
        "FM" => "Input scale or mode argument used by the selected extended dot helper.".to_owned(),
        "NELT" => "Input count of stored sparse elements for the selected helper.".to_owned(),
        "IA" | "JA" => "Input integer index storage for the selected sparse-format helper.".to_owned(),
        "ISYM" => "Input storage-symmetry selector used by the selected sparse-format helper.".to_owned(),
        _ => "Fortran scalar or array argument with the selected source-defined input/output semantics; it must be non-null and valid for the native access.".to_owned(),
    }
}

fn vector_doc(routine: &str, _argument: &str, operand: &str) -> String {
    let mutability = if routine.contains("SWAP") || routine.contains("ROT") {
        "in/out"
    } else if operand == "Y"
        && (routine.contains("AXPY")
            || routine.contains("COPY")
            || routine.contains("GEMV")
            || routine.contains("SYMV")
            || routine.contains("HEMV"))
    {
        "output or in/out"
    } else if operand == "X"
        && (routine.ends_with("SCAL")
            || routine.ends_with("SSCAL")
            || routine.ends_with("TRMV")
            || routine.ends_with("TRSV")
            || routine.ends_with("TBMV")
            || routine.ends_with("TBSV")
            || routine.ends_with("TPMV")
            || routine.ends_with("TPSV"))
    {
        "in/out"
    } else {
        "input"
    };
    format!(
        "{mutability} vector operand. For `N > 0`, make the complete source-defined strided extent accessible from the selected Fortran starting position; for a positive increment this is `1 + (N - 1) * INC{}` elements. The native routine retains no pointer.",
        if operand == "X" { "X" } else { "Y" }
    )
}

fn matrix_doc(routine: &str, operand: &str) -> String {
    let inout = (operand == "C"
        && (routine.ends_with("GEMM")
            || routine.ends_with("SYRK")
            || routine.ends_with("SYR2K")
            || routine.ends_with("HERK")
            || routine.ends_with("HER2K")))
        || (operand == "A"
            && (routine.ends_with("GER")
                || routine.ends_with("GERC")
                || routine.ends_with("GERU")
                || routine.ends_with("SYR")
                || routine.ends_with("SYR2")
                || routine.ends_with("HER")
                || routine.ends_with("HER2")))
        || (operand == "B" && (routine.ends_with("TRMM") || routine.ends_with("TRSM")));
    if inout {
        "In/out column-major matrix operand. Its leading dimension and accessible extent must satisfy the selected source for the active flags.".to_owned()
    } else {
        "Input column-major matrix operand. Its leading dimension and accessible extent must satisfy the selected source for the active flags.".to_owned()
    }
}

fn source_link(source_file: &str) -> String {
    if let Some(path) = source_file.strip_prefix("main-src/") {
        format!("https://www.netlib.org/slatec/{path}")
    } else {
        format!("https://www.netlib.org/slatec/{source_file}")
    }
}

fn strings(value: Option<&Value>) -> Vec<String> {
    value
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default()
}

fn field(value: &Value, key: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reviewed_sets_are_disjoint_and_complete() {
        let mut all = LEVEL1
            .iter()
            .chain(LEVEL2)
            .chain(LEVEL3)
            .copied()
            .collect::<Vec<_>>();
        all.sort_unstable();
        all.dedup();
        assert_eq!(all.len(), 121);
        assert_eq!(LEVEL1.len() + LEVEL2.len() + LEVEL3.len(), 121);
    }

    #[test]
    fn common_operations_have_meaningful_classification() {
        assert_eq!(operation_class("DAXPY"), "AXPY vector update");
        assert_eq!(operation_class("DGEMM"), "general matrix-matrix multiply");
        assert_eq!(operation_class("DTRSV"), "triangular solve");
    }
}
