//! Reviewed raw special-function foundation policy and rendering.
//!
//! R2B deliberately promotes the four scalar FNLIB groups already selected by
//! the public feature graph.  The catalogue's coarse precision classifier is
//! not the source of truth here: each declaration is re-exported from the
//! compiler-observed generated family module and its scalar return ABI is
//! recorded by this policy.

use crate::airy_api;
use crate::hash;
use serde_json::{Value, json};
use std::collections::BTreeMap;

/// Foundational scalar elementary functions reviewed in R2B.
pub const ELEMENTARY: &[&str] = &[
    "ALNREL", "CBRT", "COSDG", "DAWS", "DCBRT", "DCOSDG", "DDAWS", "DEXPRL", "DLNREL", "DSINDG",
    "EXPREL", "SINDG",
];

/// Foundational scalar gamma functions and directly associated utilities.
pub const GAMMA: &[&str] = &[
    "ALNGAM", "BINOM", "DBINOM", "DFAC", "DGAMI", "DGAMIC", "DGAMIT", "DGAMMA", "DGAMR", "DLNGAM",
    "DPSI", "FAC", "GAMI", "GAMIC", "GAMIT", "GAMMA", "GAMR", "PSI",
];

/// Foundational scalar beta functions.
pub const BETA: &[&str] = &["ALBETA", "BETA", "BETAI", "DBETA", "DBETAI", "DLBETA"];

/// Foundational scalar error functions.
pub const ERROR: &[&str] = &["DERF", "DERFC", "ERF", "ERFC"];

/// The complete, intentionally narrow R2B candidate set.
pub const FOUNDATIONS: &[&str] = &[
    "ALNREL", "CBRT", "COSDG", "DAWS", "DCBRT", "DCOSDG", "DDAWS", "DEXPRL", "DLNREL", "DSINDG",
    "EXPREL", "SINDG", "ALNGAM", "BINOM", "DBINOM", "DFAC", "DGAMI", "DGAMIC", "DGAMIT", "DGAMMA",
    "DGAMR", "DLNGAM", "DPSI", "FAC", "GAMI", "GAMIC", "GAMIT", "GAMMA", "GAMR", "PSI", "ALBETA",
    "BETA", "BETAI", "DBETA", "DBETAI", "DLBETA", "DERF", "DERFC", "ERF", "ERFC",
];

/// Returns the reviewed special-function subfamily for a routine.
pub fn group(routine: &str) -> Option<&'static str> {
    if ELEMENTARY.contains(&routine) {
        Some("elementary")
    } else if GAMMA.contains(&routine) {
        Some("gamma")
    } else if BETA.contains(&routine) {
        Some("beta")
    } else if ERROR.contains(&routine) {
        Some("error")
    } else {
        None
    }
}

/// Returns the canonical special-function module for a reviewed routine.
pub fn module(routine: &str) -> Option<&'static str> {
    group(routine).map(|group| match group {
        "elementary" => "special::elementary",
        "gamma" => "special::gamma",
        "beta" => "special::beta",
        "error" => "special::error",
        _ => unreachable!("known foundational group"),
    })
}

/// Returns the public and provider feature for a reviewed routine.
pub fn feature(routine: &str) -> Option<String> {
    group(routine).map(|group| format!("special-{group}"))
}

/// Source-hash guard input for the R2B foundation policy.
pub fn source_manifest(records: &[Value]) -> String {
    let mut entries = records
        .iter()
        .filter(|record| group(&field(record, "routine")).is_some())
        .filter(|record| field(record, "historical_role") == "user_callable")
        .filter(|record| field(record, "generated_declaration_status") == "generated_abi_validated")
        .map(|record| {
            format!(
                "{}\0{}\0{}\n",
                field(record, "routine"),
                field(record, "source_hash"),
                field(record, "canonical_provider"),
            )
        })
        .collect::<Vec<_>>();
    entries.sort();
    hash::bytes(entries.concat().as_bytes())
}

/// Renders the canonical reviewed `slatec_sys::special` module.
pub fn render_module(records: &[Value]) -> String {
    let mut output = String::from(
        "//! Canonical reviewed raw scalar special-function declarations.\n//!\n//! This file is generated by `slatec-corpus generate-raw-api-inventory --offline`.\n//! Each promoted special subfamily has its own source-hash-guarded review policy\n//! and re-exports one private authoritative declaration.\n\n",
    );
    for (group_name, routines) in [
        ("elementary", ELEMENTARY),
        ("gamma", GAMMA),
        ("beta", BETA),
        ("error", ERROR),
    ] {
        let cfg = if group_name == "elementary" {
            format!(
                "#[cfg(any(\n    feature = \"special-{group_name}\",\n    feature = \"raw-family-special-{group_name}\"\n))]"
            )
        } else {
            format!(
                "#[cfg(any(feature = \"special-{group_name}\", feature = \"raw-family-special-{group_name}\"))]"
            )
        };
        output.push_str(&format!(
            "/// Reviewed scalar special-function routines in the `{group_name}` group.\n{cfg}\npub mod {group_name} {{\n"
        ));
        let mut items = records
            .iter()
            .filter(|record| group(&field(record, "routine")) == Some(group_name))
            .filter(|record| {
                field(record, "reviewed_declaration_status") == "reviewed_public_driver"
            })
            .collect::<Vec<_>>();
        items.sort_by_key(|record| field(record, "routine"));
        assert_eq!(
            items.len(),
            routines.len(),
            "reviewed special-foundation policy did not render its complete group"
        );
        for record in items {
            render_routine(&mut output, record);
        }
        if output.ends_with("\n\n") {
            output.pop();
        }
        output.push_str("}\n\n");
    }
    if output.ends_with("\n\n") {
        output.pop();
    }
    output.push('\n');
    output.push_str(&airy_api::render_module(records));
    output
}

/// Creates the machine-readable R2B candidate and disposition report.
pub fn family_report(records: &[Value]) -> Value {
    let mut rows = records
        .iter()
        .filter(|record| group(&field(record, "routine")).is_some())
        .map(|record| {
            let routine = field(record, "routine");
            let spec = spec(&routine).expect("foundational routine has metadata");
            let reviewed = field(record, "reviewed_declaration_status") == "reviewed_public_driver";
            let disposition = if reviewed {
                "reviewed public driver"
            } else if field(record, "generated_declaration_status") != "generated_abi_validated" {
                "missing or ambiguous symbol"
            } else {
                "deferred pending semantic review"
            };
            json!({
                "routine":routine,
                "target_group":group(&routine),
                "purpose":spec.purpose,
                "historical_role":field(record,"historical_role"),
                "precision":spec.precision,
                "return_kind":format!("{} Fortran scalar function", spec.precision),
                "argument_abi_category":"real or INTEGER scalar values passed by address",
                "argument_order":record.get("argument_order").cloned().unwrap_or_else(|| json!([])),
                "canonical_provider":field(record,"canonical_provider"),
                "source_hash":field(record,"source_hash"),
                "source_file":field(record,"source_file"),
                "native_symbol":field(record,"native_symbol"),
                "generated_declaration_status":field(record,"generated_declaration_status"),
                "existing_family_declaration_status":field(record,"legacy_family_declaration_status"),
                "existing_safe_wrapper_audit":field(record,"safe_wrapper_status"),
                "intended_canonical_path":format!("slatec_sys::{}::{}", module(&routine).expect("group"), routine.to_ascii_lowercase()),
                "all_feature_reachability":field(record,"all_feature_reachability"),
                "provider_feature_status":field(record,"provider_feature"),
                "documentation_evidence":record.get("documentation_evidence").cloned().unwrap_or_else(|| json!({})),
                "runtime_global_state_dependencies":spec.state,
                "xerror_fnlib_dependency":spec.error,
                "final_feasibility_disposition":disposition,
                "exclusion_or_deferment_reason":if reviewed { "none".to_owned() } else { field(record,"exclusion_reason") },
            })
        })
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| left["routine"].as_str().cmp(&right["routine"].as_str()));
    let counts = rows
        .iter()
        .fold(BTreeMap::<String, usize>::new(), |mut counts, row| {
            *counts
                .entry(field(row, "final_feasibility_disposition"))
                .or_default() += 1;
            counts
        });
    json!({
        "schema_id":"slatec-sys.raw-api.special-foundations-report",
        "schema_version":"1.0.0",
        "scope":"Every R2B foundational scalar special-function identity selected by the authored elementary, gamma, beta, and error taxonomy.",
        "candidate_count":rows.len(),
        "disposition_counts":counts,
        "records":rows,
    })
}

fn render_routine(output: &mut String, record: &Value) {
    let routine = field(record, "routine");
    let spec = spec(&routine).expect("foundational routine has metadata");
    let group = group(&routine).expect("foundational routine has group");
    let source_file = field(record, "source_file");
    let source_link = format!("https://www.netlib.org/slatec/{source_file}");
    output.push_str(&format!("    // raw-api-routine: {routine}\n"));
    doc_line(output, &format!("Original SLATEC routine `{routine}`."));
    doc_line(output, spec.purpose);
    doc_line(
        output,
        &format!("Mathematical operation: {}.", spec.operation),
    );
    doc_line(
        output,
        &format!(
            "Precision and return ABI: `{}` Fortran scalar function returned directly by the supported GNU MinGW ABI.",
            spec.precision
        ),
    );
    doc_line(
        output,
        &format!("Domain and exceptional behavior: {}", spec.domain),
    );
    doc_line(
        output,
        &format!(
            "Selected provider: `{}`; source: <{source_link}>; native symbol: `{}`.",
            field(record, "canonical_provider"),
            field(record, "native_symbol")
        ),
    );
    doc_line(
        output,
        "Supported ABI profile: `ffi-profile-gnu-mingw-x86_64`; every Fortran scalar input is passed by address.",
    );
    doc_line(output, "");
    doc_line(output, "# Arguments");
    for argument in strings(record.get("argument_order")) {
        doc_line(
            output,
            &format!("- `{argument}`: {}", argument_doc(&routine, &argument)),
        );
    }
    doc_line(output, "");
    doc_line(output, "# Native behavior");
    doc_line(output, spec.error);
    doc_line(output, spec.state);
    doc_line(output, "");
    doc_line(output, "# Safety");
    doc_line(
        output,
        "Every argument pointer must be non-null, correctly aligned, and readable as its documented scalar type for the complete call; no pointer is retained and these functions have no output pointer. The caller must link a provider built for the documented GNU MinGW ABI and must not allow a panic or other unwinding to cross this FFI boundary. Stay inside the documented native domain and avoid inputs that can trigger fatal legacy XERROR behavior. FNLIB initialization and legacy error controls are process-global; this raw declaration does not serialize calls, so callers must provide required process-wide synchronization.",
    );
    output.push_str(&format!(
        "    #[doc(inline)]\n    pub use crate::families::special_{group}::{};\n\n",
        routine.to_ascii_lowercase()
    ));
}

fn doc_line(output: &mut String, text: &str) {
    if text.is_empty() {
        output.push_str("    ///\n");
    } else {
        output.push_str("    /// ");
        output.push_str(text);
        output.push('\n');
    }
}

fn argument_doc(routine: &str, argument: &str) -> &'static str {
    match argument {
        "X" => {
            "input real scalar, passed by address; null is not permitted, the value is read only, and it must satisfy the routine's documented domain."
        }
        "A" if matches!(
            routine,
            "DGAMI" | "DGAMIC" | "DGAMIT" | "GAMI" | "GAMIC" | "GAMIT"
        ) =>
        {
            "input real shape parameter, passed by address; null is not permitted, the value is read only, and the reviewed direct-call domain requires `A > 0`."
        }
        "A" => {
            "first input real parameter, passed by address; null is not permitted, the value is read only, and the documented beta-function domain requires it to be positive."
        }
        "B" => {
            "second input real parameter, passed by address; null is not permitted, the value is read only, and the documented beta-function domain requires it to be positive."
        }
        "PIN" => {
            "first positive beta-distribution shape parameter, passed by address; null is not permitted and the value is read only."
        }
        "QIN" => {
            "second positive beta-distribution shape parameter, passed by address; null is not permitted and the value is read only."
        }
        "N" => {
            "input `FortranInteger`, passed by address; null is not permitted, the value is read only, and it must be non-negative and within the routine's finite-result range."
        }
        "M" => {
            "input `FortranInteger`, passed by address; null is not permitted, the value is read only, and it must satisfy `0 <= M <= N`."
        }
        _ => {
            "input scalar, passed by address; null is not permitted and the value is read only for the complete call."
        }
    }
}

struct Spec {
    routine: &'static str,
    precision: &'static str,
    purpose: &'static str,
    operation: &'static str,
    domain: &'static str,
    error: &'static str,
    state: &'static str,
}

const FNLIB_STATE: &str = "FNLIB may initialize saved coefficients and machine constants on first use; it is not documented as thread-safe by this raw interface.";
const XERROR_DOMAIN: &str = "The selected source reports documented domain, overflow, underflow, or precision conditions through legacy XERROR/XERMSG; a raw caller must avoid fatal configurations and does not receive a Rust error value.";
const GAMR_STATE: &str = "This routine reads and temporarily changes legacy XERROR control with XGETF/XSETF and clears selected reports with XERCLR; serialize it with every other call that can use the legacy error runtime.";

const SPECS: &[Spec] = &[
    Spec {
        routine: "ALNREL",
        precision: "f32",
        purpose: "Evaluates `ln(1 + x)` with relative-error accuracy near zero.",
        operation: "natural logarithm of one plus the argument",
        domain: "`X` must be greater than `-1`; extremely small positive `1 + X` can report loss of precision.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "CBRT",
        precision: "f32",
        purpose: "Computes the real cube root.",
        operation: "real cube root",
        domain: "finite real inputs are supported, including negative values and zero.",
        error: "The source uses machine constants but documents no routine-specific XERROR domain rejection for ordinary finite inputs.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "COSDG",
        precision: "f32",
        purpose: "Computes cosine with the argument expressed in degrees.",
        operation: "cosine of degrees converted to radians",
        domain: "ordinary finite real degree arguments are supported; very large magnitudes inherit native argument-reduction precision limits.",
        error: "The source does not report ordinary finite inputs through XERROR.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DAWS",
        precision: "f32",
        purpose: "Computes Dawson's integral for a real argument.",
        operation: "exp(-x²) times the integral of exp(t²) from zero to x",
        domain: "finite real inputs are supported; sufficiently large magnitude can underflow and report through XERROR.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DCBRT",
        precision: "f64",
        purpose: "Computes the double-precision real cube root.",
        operation: "real cube root",
        domain: "finite real inputs are supported, including negative values and zero.",
        error: "The source uses machine constants but documents no routine-specific XERROR domain rejection for ordinary finite inputs.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DCOSDG",
        precision: "f64",
        purpose: "Computes double-precision cosine with the argument expressed in degrees.",
        operation: "cosine of degrees converted to radians",
        domain: "ordinary finite real degree arguments are supported; very large magnitudes inherit native argument-reduction precision limits.",
        error: "The source does not report ordinary finite inputs through XERROR.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DDAWS",
        precision: "f64",
        purpose: "Computes the double-precision Dawson integral.",
        operation: "exp(-x²) times the integral of exp(t²) from zero to x",
        domain: "finite real inputs are supported; sufficiently large magnitude can underflow and report through XERROR.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DEXPRL",
        precision: "f64",
        purpose: "Computes the relative exponential accurately near zero.",
        operation: "(exp(x) - 1) / x with the continuous value one at zero",
        domain: "finite real inputs are supported; large positive inputs can overflow in the native exponential.",
        error: "The source uses machine constants; overflow follows the native floating-point/runtime behavior.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DLNREL",
        precision: "f64",
        purpose: "Evaluates double-precision `ln(1 + x)` with relative-error accuracy near zero.",
        operation: "natural logarithm of one plus the argument",
        domain: "`X` must be greater than `-1`; extremely small positive `1 + X` can report loss of precision.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DSINDG",
        precision: "f64",
        purpose: "Computes double-precision sine with the argument expressed in degrees.",
        operation: "sine of degrees converted to radians",
        domain: "ordinary finite real degree arguments are supported; very large magnitudes inherit native argument-reduction precision limits.",
        error: "The source does not report ordinary finite inputs through XERROR.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "EXPREL",
        precision: "f32",
        purpose: "Computes the relative exponential accurately near zero.",
        operation: "(exp(x) - 1) / x with the continuous value one at zero",
        domain: "finite real inputs are supported; large positive inputs can overflow in the native exponential.",
        error: "The source uses machine constants; overflow follows the native floating-point/runtime behavior.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "SINDG",
        precision: "f32",
        purpose: "Computes sine with the argument expressed in degrees.",
        operation: "sine of degrees converted to radians",
        domain: "ordinary finite real degree arguments are supported; very large magnitudes inherit native argument-reduction precision limits.",
        error: "The source does not report ordinary finite inputs through XERROR.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "ALNGAM",
        precision: "f32",
        purpose: "Computes the logarithm of the absolute value of Gamma.",
        operation: "ln(abs(Gamma(x)))",
        domain: "avoid Gamma poles at zero and negative integers, arguments too near a pole, and magnitudes that overflow the selected source range.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "BINOM",
        precision: "f32",
        purpose: "Computes a binomial coefficient.",
        operation: "N! / (M! (N-M)!)",
        domain: "requires integer `N >= 0` and `0 <= M <= N`; a result outside the native finite range reports overflow.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DBINOM",
        precision: "f64",
        purpose: "Computes a double-precision binomial coefficient.",
        operation: "N! / (M! (N-M)!)",
        domain: "requires integer `N >= 0` and `0 <= M <= N`; a result outside the native finite range reports overflow.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DFAC",
        precision: "f64",
        purpose: "Computes a double-precision factorial.",
        operation: "N factorial",
        domain: "requires integer `N >= 0` and a result within the native finite range.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DGAMI",
        precision: "f64",
        purpose: "Computes the lower incomplete Gamma integral.",
        operation: "integral from zero to x of exp(-t) t^(a-1)",
        domain: "the reviewed direct-call domain requires `A > 0` and `X >= 0`.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DGAMIC",
        precision: "f64",
        purpose: "Computes the complementary incomplete Gamma integral.",
        operation: "integral from x to infinity of exp(-t) t^(a-1)",
        domain: "the reviewed direct-call domain requires `A > 0` and `X >= 0`; near-cancellation or underflow can be reported.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DGAMIT",
        precision: "f64",
        purpose: "Computes Tricomi's incomplete Gamma function.",
        operation: "x^(-a) times the lower incomplete Gamma integral",
        domain: "the reviewed direct-call domain requires `A > 0` and `X >= 0`; do not assume unreviewed analytic-continuation behavior.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DGAMMA",
        precision: "f64",
        purpose: "Computes the complete Gamma function.",
        operation: "Gamma(x)",
        domain: "`X` must not be zero or a negative integer; avoid arguments too near a pole and values whose result overflows or underflows.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DGAMR",
        precision: "f64",
        purpose: "Computes the reciprocal Gamma function.",
        operation: "1 / Gamma(x)",
        domain: "finite real arguments are supported by the selected source; nonpositive integer poles produce its documented zero result, while near-pole and range behavior remains native.",
        error: "The implementation deliberately suppresses selected Gamma diagnostics with XERCLR while evaluating its result; callers must account for legacy XERROR state.",
        state: GAMR_STATE,
    },
    Spec {
        routine: "DLNGAM",
        precision: "f64",
        purpose: "Computes the logarithm of the absolute value of double-precision Gamma.",
        operation: "ln(abs(Gamma(x)))",
        domain: "avoid Gamma poles at zero and negative integers, arguments too near a pole, and magnitudes outside the selected source range.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DPSI",
        precision: "f64",
        purpose: "Computes the double-precision digamma function.",
        operation: "derivative of ln(Gamma(x))",
        domain: "`X` must not be zero or a negative integer; avoid values too near a pole.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "FAC",
        precision: "f32",
        purpose: "Computes a factorial.",
        operation: "N factorial",
        domain: "requires integer `N >= 0` and a result within the native finite range.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "GAMI",
        precision: "f32",
        purpose: "Computes the lower incomplete Gamma integral.",
        operation: "integral from zero to x of exp(-t) t^(a-1)",
        domain: "the reviewed direct-call domain requires `A > 0` and `X >= 0`.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "GAMIC",
        precision: "f32",
        purpose: "Computes the complementary incomplete Gamma integral.",
        operation: "integral from x to infinity of exp(-t) t^(a-1)",
        domain: "the reviewed direct-call domain requires `A > 0` and `X >= 0`; near-cancellation or underflow can be reported.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "GAMIT",
        precision: "f32",
        purpose: "Computes Tricomi's incomplete Gamma function.",
        operation: "x^(-a) times the lower incomplete Gamma integral",
        domain: "the reviewed direct-call domain requires `A > 0` and `X >= 0`; do not assume unreviewed analytic-continuation behavior.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "GAMMA",
        precision: "f32",
        purpose: "Computes the complete Gamma function.",
        operation: "Gamma(x)",
        domain: "`X` must not be zero or a negative integer; avoid arguments too near a pole and values whose result overflows or underflows.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "GAMR",
        precision: "f32",
        purpose: "Computes the reciprocal Gamma function.",
        operation: "1 / Gamma(x)",
        domain: "finite real arguments are supported by the selected source; nonpositive integer poles produce its documented zero result, while near-pole and range behavior remains native.",
        error: "The implementation deliberately suppresses selected Gamma diagnostics with XERCLR while evaluating its result; callers must account for legacy XERROR state.",
        state: GAMR_STATE,
    },
    Spec {
        routine: "PSI",
        precision: "f32",
        purpose: "Computes the digamma function.",
        operation: "derivative of ln(Gamma(x))",
        domain: "`X` must not be zero or a negative integer; avoid values too near a pole.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "ALBETA",
        precision: "f32",
        purpose: "Computes the natural logarithm of the complete Beta function.",
        operation: "ln(Beta(a, b))",
        domain: "both `A` and `B` must be positive.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "BETA",
        precision: "f32",
        purpose: "Computes the complete Beta function.",
        operation: "Gamma(a) Gamma(b) / Gamma(a + b)",
        domain: "both `A` and `B` must be positive; overflow or underflow follows the selected source's XERROR behavior.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "BETAI",
        precision: "f32",
        purpose: "Computes the regularized incomplete Beta ratio.",
        operation: "probability integral of a Beta(PIN, QIN) variate through X",
        domain: "requires `0 <= X <= 1`, `PIN > 0`, and `QIN > 0`.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DBETA",
        precision: "f64",
        purpose: "Computes the double-precision complete Beta function.",
        operation: "Gamma(a) Gamma(b) / Gamma(a + b)",
        domain: "both `A` and `B` must be positive; overflow or underflow follows the selected source's XERROR behavior.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DBETAI",
        precision: "f64",
        purpose: "Computes the double-precision regularized incomplete Beta ratio.",
        operation: "probability integral of a Beta(PIN, QIN) variate through X",
        domain: "requires `0 <= X <= 1`, `PIN > 0`, and `QIN > 0`.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DLBETA",
        precision: "f64",
        purpose: "Computes the double-precision natural logarithm of the complete Beta function.",
        operation: "ln(Beta(a, b))",
        domain: "both `A` and `B` must be positive.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DERF",
        precision: "f64",
        purpose: "Computes the double-precision error function.",
        operation: "2/sqrt(pi) times the integral of exp(-t²) from zero to x",
        domain: "finite real inputs are supported; ordinary finite inputs do not have a mathematical domain error.",
        error: "The source initializes saved coefficients; its complementary-function path handles tail underflow according to the native floating-point behavior.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "DERFC",
        precision: "f64",
        purpose: "Computes the double-precision complementary error function.",
        operation: "1 - erf(x)",
        domain: "finite real inputs are supported; sufficiently large positive inputs can underflow and report through XERROR.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
    Spec {
        routine: "ERF",
        precision: "f32",
        purpose: "Computes the error function.",
        operation: "2/sqrt(pi) times the integral of exp(-t²) from zero to x",
        domain: "finite real inputs are supported; ordinary finite inputs do not have a mathematical domain error.",
        error: "The source initializes saved coefficients; its complementary-function path handles tail underflow according to the native floating-point behavior.",
        state: FNLIB_STATE,
    },
    Spec {
        routine: "ERFC",
        precision: "f32",
        purpose: "Computes the complementary error function.",
        operation: "1 - erf(x)",
        domain: "finite real inputs are supported; sufficiently large positive inputs can underflow and report through XERROR.",
        error: XERROR_DOMAIN,
        state: FNLIB_STATE,
    },
];

fn spec(routine: &str) -> Option<&'static Spec> {
    SPECS.iter().find(|spec| spec.routine == routine)
}

fn field(value: &Value, key: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_owned()
}

fn strings(value: Option<&Value>) -> Vec<String> {
    value
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default()
}
